=== ZKLlab/shuosc-books/schema/metadata.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Metadata",
  "description": "SHUOSC图书元信息",
  "type": "object",
  "properties": {
    "isbn": {
      "description": "ISBN号",
      "type": "string",
      "pattern": "^978\\d{10}$"
    },
    "title": {
      "description": "题名",
      "type": "string"
    },
    "parallelTitle": {
      "description": "并列题名",
      "type": [
        "string",
        "null"
      ]
    },
    "seriesTitle": {
      "description": "丛书名",
      "type": [
        "string",
        "null"
      ]
    },
    "author": {
      "description": "责任者",
      "type": "string"
    },
    "languageCode": {
      "description": "正文语种",
      "type": "string",
      "pattern": "^[a-z]{3}$"
    },
    "description": {
      "description": "内容简介",
      "type": "string"
    },
    "publisher": {
      "description": "出版社",
      "type": "string"
    },
    "clcNumber": {
      "description": "中图分类号",
      "type": [
        "string",
        "null"
      ]
    },
    "publicationDate": {
      "description": "出版时间",
      "type": "string",
      "pattern": "^\\d{4}-(0\\d|1[012])$"
    },
    "pricing": {
      "description": "定价",
      "type": "string",
      "pattern": "^([1-9]\\d*|0)\\.\\d{2}$"
    },
    "totalPages": {
      "description": "页数",
      "type": "string",
      "pattern": "^[1-9]\\d*$"
    },
    "binding": {
      "description": "装帧",
      "type": "string"
    },
    "suitFlag": {
      "type": "boolean"
    }
  },
  "required": [
    "isbn",
    "title",
    "parallelTitle",
    "seriesTitle",
    "author",
    "languageCode",
    "description",
    "publisher",
    "clcNumber",
    "publicationDate",
    "pricing",
    "totalPages",
    "binding",
    "suitFlag"
  ],
  "additionalProperties": false
}

=== ZKLlab/shuosc-books/data/metadata/9787111251217__编译原理__第2版.json
{
  "isbn": "9787111251217",
  "title": "编译原理 (第2版)",
  "parallelTitle": "Compilers: Principles, Techniques, and Tools",
  "seriesTitle": "计算机科学丛书",
  "author": "[美] Alfred V. Aho, Monica S. Lam, Ravi Sethi 著; 赵建华, 郑滔, 戴新宇 译",
  "languageCode": "chi",
  "description": "本书全面、深入地探讨了编译器设计方面的重要主题，包括词法分析、语法分析、语法制导定义和语法制导翻译、运行时刻环境、目标代码生成、代码优化技术、并行性检测以及过程间分析技术，并在相关章节中给出大量实例。",
  "publisher": "机械工业出版社",
  "clcNumber": "TP314",
  "publicationDate": "2009-01",
  "pricing": "89.00",
  "totalPages": "631",
  "binding": "平装",
  "suitFlag": false
}

=== ZKLlab/shuosc-books/data/metadata/9787115516756__UNIX环境高级编程__第3版.json
{
  "isbn": "9787115516756",
  "title": "UNIX环境高级编程 (第3版)",
  "parallelTitle": "Advanced Programming in the UNIX Environment",
  "seriesTitle": null,
  "author": "[美] W. Richard Stevens, Stephen A. Rago 著; 戚正伟, 张亚英, 尤晋元 译",
  "languageCode": "chi",
  "description": "书中除了介绍UNIX文件和目录、标准I/O库、系统数据文件和信息、进程环境、进程控制、进程关系、信号、线程、线程控制、守护进程、各种I/O、进程间通信、网络IPC、伪终端等方面的内容，还在此基础上介绍了众多应用实例，包括如何创建数据库函数库以及如何与网络打印机通信等。此外，还在附录中给出了函数原型和部分习题的答案。",
  "publisher": "人民邮电出版社",
  "clcNumber": "TP316.81",
  "publicationDate": "2019-10",
  "pricing": "169.00",
  "totalPages": "812",
  "binding": "平装",
  "suitFlag": false
}

=== ZKLlab/shuosc-books/data/metadata/9787111666073__现代操作系统__原理与实现.json
{
  "isbn": "9787111666073",
  "title": "现代操作系统: 原理与实现",
  "parallelTitle": null,
  "seriesTitle": "计算机类专业系统能力培养系列教材",
  "author": "陈海波, 夏虞斌 著",
  "languageCode": "chi",
  "description": "本书以三个“面向”为导向，即面向经典基础理论与方法，面向国际前沿研究，面向最新工业界实践，深入浅出地介绍操作系统的理论、架构、设计方法与具体实现。本书是首本以ARM64为主体介绍操作系统的教材，将学术前沿与工业实践充分结合,不仅介绍了现有的Linux宏内核操作系统架构，而且介绍了微内核、外核等操作系统架构。本书共分为三个部分，其中第一部分(操作系统基础)以纸质版的形式出版，第二部分（操作系统进阶）和第三部分（ChCore课程实验）则以电子版的形式在本书网站发布。第一部分共分为11章，内容包括：操作系统概述、硬件结构、操作系统结构、内存管理、进程与线程、操作系统调度、进程间通信、同步原语、文件系统与存储、设备管理和系统虚拟化。本书包含大量插图、示例和练习，并融入了典型的操作系统相关的技术问题，既可以作为高等院校计算机专业本科生和研究生的操作系统课程教材，也可以作为工业界从事操作系统相关领域研发工作的专业人员的参考书。",
  "publisher": "机械工业出版社",
  "clcNumber": "TP316",
  "publicationDate": "2020-10",
  "pricing": "79.00",
  "totalPages": "376",
  "binding": "平装",
  "suitFlag": false
}

=== ZKLlab/shuosc-books/data/metadata/9787115508652__重构__改善既有代码的设计__第2版.json
{
  "isbn": "9787115508652",
  "title": "重构: 改善既有代码的设计 (第2版)",
  "parallelTitle": "Refactoring: Improving the Design of Existing Code",
  "seriesTitle": null,
  "author": "[美] Martin Fowler 著; 熊节, 林从羽 译",
  "languageCode": "chi",
  "description": "本书清晰揭示了重构的过程，解释了重构的原理和最佳实践方式，并给出了何时以及何地应该开始挖掘代码以求改善。书中给出了60多个可行的重构，每个重构都介绍了一种经过验证的代码变换手法的动机和技术。本书提出的重构准则将帮助你一次一小步地修改你的代码，从而减少了开发过程中的风险。",
  "publisher": "人民邮电出版社",
  "clcNumber": "TP311.11",
  "publicationDate": "2019-04",
  "pricing": "99.00",
  "totalPages": "422",
  "binding": "平装",
  "suitFlag": false
}

=== ZKLlab/shuosc-books/data/metadata/9787121181184__编码__隐匿在计算机软硬件背后的语言.json
{
  "isbn": "9787121181184",
  "title": "编码: 隐匿在计算机软硬件背后的语言",
  "parallelTitle": "Code: The Hidden Language of Computer Hardware and Software",
  "seriesTitle": "传世经典书丛",
  "author": "[美] Charles Petzold 著; 左飞, 薛佟佟 译",
  "languageCode": "chi",
  "description": "本书是一本讲述计算机工作原理的书。不过，你千万不要因为“工作原理”之类的字眼就武断地认为，它是晦涩而难懂的。作者用丰富的想象和清晰的笔墨将看似繁杂的理论阐述得通俗易懂，你丝毫不会感到枯燥和生硬。更重要的是，你会因此而获得对计算机工作原理较深刻的理解。这种理解不是抽象层面上的，而是具有一定深度的，这种深度甚至不逊于“电气工程师”和“程序员”的理解。",
  "publisher": "电子工业出版社",
  "clcNumber": "TP3-0",
  "publicationDate": "2012-10",
  "pricing": "59.00",
  "totalPages": "420",
  "binding": "平装",
  "suitFlag": false
}

=== ZKLlab/shuosc-books/data/metadata/9787111617778__TCP_IP详解__卷3_TCP事务协议_HTTP_NNTP和UNIX域协议.json
{
  "isbn": "9787111617778",
  "title": "TCP/IP详解 卷3: TCP事务协议、HTTP、NNTP和UNIX域协议",
  "parallelTitle": "TCP/IP Illustrated, Volume 3: TCP for Transactions, HTTP, NNTP, and the UNIX Domain Protocols",
  "seriesTitle": "计算机科学丛书",
  "author": "[美] Gary R. Wright, W. Richard Stevens 著; 胡谷雨, 吴礼发 等译",
  "languageCode": "chi",
  "description": "本书是三卷本套书《TCP/IP详解》的第3卷，主要内容包括：TCP事务协议，即T/TCP，这是对TCP的扩展，使客户-服务器事务更快、更高效和更可靠；TCP/IP应用，主要是HTTP和NNTP；Unix域协议，这些协议提供了进程之间通信的一种手段，当客户与服务器进程在同一台主机上时，Unix域协议通常要比TCP/IP快1倍。本书同样采用了大量的实例和实现细节，并参考引用了卷2中的大量源程序。",
  "publisher": "机械工业出版社",
  "clcNumber": "TN915.04",
  "publicationDate": "2019-03",
  "pricing": "59.00",
  "totalPages": "266",
  "binding": "平装",
  "suitFlag": true
}

=== ZKLlab/shuosc-books/data/metadata/9787115367181__Haskell并行与并发编程.json
{
  "isbn": "9787115367181",
  "title": "Haskell并行与并发编程",
  "parallelTitle": "Parallel and Concurrent Programming in Haskell",
  "seriesTitle": null,
  "author": "[英] Simon Marlow 著; 喻昌远 译",
  "languageCode": "chi",
  "description": "本书深入浅出地介绍如何使用Haskell语言及相关的库和框架编写并行和并发程序。本书用两个部分分别讲解并行Haskell编程和并发Haskell编程。书中包含大量可运行的代码示例，并附有详细的注释，读者通过亲身运行、修改和调试代码，可极大地加深对书中内容的理解。",
  "publisher": "人民邮电出版社",
  "clcNumber": "TP311.1",
  "publicationDate": "2014-09",
  "pricing": "59.00",
  "totalPages": "259",
  "binding": "平装",
  "suitFlag": false
}

=== ZKLlab/shuosc-books/data/metadata/9787115400512__程序员的数学__2_概率统计.json
{
  "isbn": "9787115400512",
  "title": "程序员的数学 2: 概率统计",
  "parallelTitle": null,
  "seriesTitle": "图灵程序设计丛书",
  "author": "[日] 平冈和幸, 堀玄 著; 陈筱烟 译",
  "languageCode": "chi",
  "description": "本书沿袭《程序员的数学》平易近人的风格，用通俗的语言和具体的图表深入讲解程序员必须掌握的各类概率统计知识，例证丰富，讲解明晰，且提供了大量扩展内容，引导读者进一步深入学习。 本书涉及概率变量、贝叶斯公式、离散型概率分布、连续型概率分布、伪随机数、协方差矩阵、估计检验以及与之相关的各类应用。",
  "publisher": "人民邮电出版社",
  "clcNumber": "TP301.6",
  "publicationDate": "2015-09",
  "pricing": "79.00",
  "totalPages": "405",
  "binding": "平装",
  "suitFlag": true
}
