=== ZKLlab/shuosc-books/schema/metadata.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Metadata",
  "description": "SHUOSC图书元信息",
  "type": "object",
  "properties": {
    "isbn": {
      "description": "ISBN号",
      "type": "string",
      "pattern": "^978\\d{10}$"
    },
    "title": {
      "description": "题名",
      "type": "string"
    },
    "parallelTitle": {
      "description": "并列题名",
      "type": [
        "string",
        "null"
      ]
    },
    "seriesTitle": {
      "description": "丛书名",
      "type": [
        "string",
        "null"
      ]
    },
    "author": {
      "description": "责任者",
      "type": "string"
    },
    "languageCode": {
      "description": "正文语种",
      "type": "string",
      "pattern": "^[a-z]{3}$"
    },
    "description": {
      "description": "内容简介",
      "type": "string"
    },
    "publisher": {
      "description": "出版社",
      "type": "string"
    },
    "clcNumber": {
      "description": "中图分类号",
      "type": [
        "string",
        "null"
      ]
    },
    "publicationDate": {
      "description": "出版时间",
      "type": "string",
      "pattern": "^\\d{4}-(0\\d|1[012])$"
    },
    "pricing": {
      "description": "定价",
      "type": "string",
      "pattern": "^([1-9]\\d*|0)\\.\\d{2}$"
    },
    "totalPages": {
      "description": "页数",
      "type": "string",
      "pattern": "^[1-9]\\d*$"
    },
    "binding": {
      "description": "装帧",
      "type": "string"
    },
    "suitFlag": {
      "type": "boolean"
    }
  },
  "required": [
    "isbn",
    "title",
    "parallelTitle",
    "seriesTitle",
    "author",
    "languageCode",
    "description",
    "publisher",
    "clcNumber",
    "publicationDate",
    "pricing",
    "totalPages",
    "binding",
    "suitFlag"
  ],
  "additionalProperties": false
}

=== ZKLlab/shuosc-books/data/metadata/9787115517791__UNIX网络编程__卷1_套接字联网API__第3版.json
{
  "isbn": "9787115517791",
  "title": "UNIX网络编程 卷1: 套接字联网API (第3版)",
  "parallelTitle": "UNIX Network Programming, Volume 1: The Sockets Networking API",
  "seriesTitle": null,
  "author": "[美] W. Richard Stevens, Bill Fenner, Andrew M. Rudoff 著",
  "languageCode": "chi",
  "description": "本书是一部UNIX网络编程的经典之作！书中全面深入地介绍了如何使用套接字API进行网络编程。全书不但介绍了基本编程内容，还涵盖了与套接字编程相关的高级主题，对于客户/服务器程序的各种设计方法也作了完整的探讨，最后还深入分析了流这种设备驱动机制。本书内容详尽且具权威性，几乎每章都提供精选的习题，并提供了部分习题的答案，是网络研究和开发人员理想的参考书。",
  "publisher": "人民邮电出版社",
  "clcNumber": "TP316.81",
  "publicationDate": "2019-12",
  "pricing": "169.00",
  "totalPages": "806",
  "binding": "平装",
  "suitFlag": true
}

=== ZKLlab/shuosc-books/data/metadata/9787111670513__编程与类型系统.json
{
  "isbn": "9787111670513",
  "title": "编程与类型系统",
  "parallelTitle": "Programming with Types: Examples in TypeScript",
  "seriesTitle": "华章程序员书库",
  "author": "[美] Vlad Riscutia 著; 赵利通 译",
  "languageCode": "chi",
  "description": "本书旨在告诉读者如何使用类型系统编写更好、更安全的代码，全面介绍类型系统的特性，主要内容包括类型和类型系统简介、基本类型、类型组合、类型安全、函数类型及其高级应用、子类型和类型兼容、面向对象编程的关键元素、泛型数据结构、泛型算法和迭代器、高阶类型等。本书没有关注这些特性背后的理论，而是通过实际应用的方式来解释每种特性，说明如何以及何时使用每种特性来改进代码。本书适合具备一定面向对象编程经验的读者阅读。",
  "publisher": "机械工业出版社",
  "clcNumber": "TP311.1",
  "publicationDate": "2021-01",
  "pricing": "119.00",
  "totalPages": "298",
  "binding": "平装",
  "suitFlag": false
}

=== ZKLlab/shuosc-books/data/metadata/9787560926995__STL源码剖析.json
{
  "isbn": "9787560926995",
  "title": "STL源码剖析",
  "parallelTitle": "The Annotated STL Sources (using SGISTL)",
  "seriesTitle": null,
  "author": "侯捷 著",
  "languageCode": "chi",
  "description": "本书是面向C++中高级程序员的技术专著。STL的含义是标准模板库。STL（标准模板库）是在加利褔尼亚州的惠普实验室中开发的一系列软件的统称，其中的代码采用了模板类及模板函数的方式，相对于传统的由函数和类组成的库来说，可以提供更好的代码作用。1994年7月，被美国国家标准学会纳入C++标准。",
  "publisher": "华中科技大学出版社",
  "clcNumber": "TP312",
  "publicationDate": "2002-06",
  "pricing": "68.00",
  "totalPages": "493",
  "binding": "平装",
  "suitFlag": false
}

=== ZKLlab/shuosc-books/data/metadata/9787519817749__Effective_Modern_C__42招独家技巧助您改善C_11和C_14的高效用法__中文版.json
{
  "isbn": "9787519817749",
  "title": "Effective Modern C++: 42招独家技巧助您改善C++11和C++14的高效用法 (中文版)",
  "parallelTitle": "Effective Modern C++",
  "seriesTitle": null,
  "author": "[美] Scott Meyers 著; 高博 译",
  "languageCode": "chi",
  "description": "想要彻底理解C++11和C++14，不可止步于熟悉它们引入的语言特性（例如，auto型别推导、移动语义、lambda表达式以及并发支持）。挑战在于高效地运用这些特性——从而使你的软件具备正确性、高效率、可维护性和可移植性。这正是这本实用的图书意欲达成的定位。它描述的正是使用C++11和C++14（即现代C++）来撰写真正卓越的软件之道。涵盖以下主题:大括号初始化、noexcept规格、完美转发，以及智能指针的make函数的优缺点。std::move、std::forward、右值引用和万能引用之间的联系。撰写整洁、正确，以及高效的lambda表达式的方法。std::atomic和volatile有怎样的区别，它们分别用于什么场合，以及它们和C++的并发API有何联系。“旧”C++程序设计（即C++98）中的最佳实战要求在现代C++的软件开发中作出哪些修订。",
  "publisher": "中国电力出版社",
  "clcNumber": "TP312.8",
  "publicationDate": "2018-02",
  "pricing": "99.00",
  "totalPages": "290",
  "binding": "平装",
  "suitFlag": false
}

=== ZKLlab/shuosc-books/data/metadata/9787111544937__深入理解计算机系统__原书第3版.json
{
  "isbn": "9787111544937",
  "title": "深入理解计算机系统 (原书第3版)",
  "parallelTitle": "Computer Systems: A Programmer's Perspective",
  "seriesTitle": "计算机科学丛书",
  "author": "[美] Randal E. Bryant, David R. O’Hallaron 著; 龚奕利, 贺莲 译",
  "languageCode": "chi",
  "description": "本书是将计算机软件和硬件理论结合讲述的经典教程，内容覆盖计算机导论、体系结构和处理器设计等多门课程。本书的最大优点是为程序员描述计算机系统的实现细节，通过描述程序是如何映射到系统上，以及程序是如何执行的，使读者更好地理解程序的行为为什么是这样的，以及造成效率低下的原因。",
  "publisher": "机械工业出版社",
  "clcNumber": "TP338",
  "publicationDate": "2016-11",
  "pricing": "139.00",
  "totalPages": "737",
  "binding": "平装",
  "suitFlag": false
}

=== ZKLlab/shuosc-books/data/metadata/9787302392644__人月神话__40周年中文纪念版.json
{
  "isbn": "9787302392644",
  "title": "人月神话 (40周年中文纪念版)",
  "parallelTitle": "The Mythical Man-Month: Essays on Software Engineering",
  "seriesTitle": null,
  "author": "[美] Frederick P. Brooks, Jr. 著; UML China翻译组, 汪颖 译",
  "languageCode": "chi",
  "description": "在软件领域，很少能有像《人月神话》一样具有深远影响力并且畅销不衰的著作。该书英文原版一经面世，即引起业内人士的强烈反响，后又译为德、法、日、俄中等多种语言，全球销量数百万册。在本书第一次出版38年后的今天，我们重新整理了Brooks博士的经典内容，并将国内、国外软件开发领域先行者们对《人月神话》中的实践及系统理论的使用经验和心得集结成册与大家共享，更使本书成为国内从业者的必读经典之一。",
  "publisher": "清华大学出版社",
  "clcNumber": "TP311.5",
  "publicationDate": "2015-04",
  "pricing": "68.00",
  "totalPages": "392",
  "binding": "平装",
  "suitFlag": false
}

=== ZKLlab/shuosc-books/data/metadata/9787115517807__UNIX网络编程__卷2_进程间通信__第2版.json
{
  "isbn": "9787115517807",
  "title": "UNIX网络编程 卷2: 进程间通信 (第2版)",
  "parallelTitle": "UNIX Network Programming, Volume 2: Interprocess Communications",
  "seriesTitle": null,
  "author": "[美] W. Richard Stevens 著",
  "languageCode": "chi",
  "description": "本书是一部UNIX网络编程的经典之作！进程间通信（IPC）几乎是所有Unix程序性能的关键，理解IPC也是理解如何开发不同主机间网络应用程序的必要条件。本书从对Posix IPC 和System V IPC的内部结构开始讨论，全面深入地介绍了4种IPC形式：消息传递、同步、共享内存及远程过程调用。本书内容详尽且具权威性，几乎每章都提供精选的习题，并提供了部分习题的答案。",
  "publisher": "人民邮电出版社",
  "clcNumber": "TP316.81",
  "publicationDate": "2019-12",
  "pricing": "109.00",
  "totalPages": "417",
  "binding": "平装",
  "suitFlag": true
}

=== ZKLlab/shuosc-books/data/metadata/9787121123320__Effective_C__改善程序与设计的55个具体做法__第三版.json
{
  "isbn": "9787121123320",
  "title": "Effective C++: 改善程序与设计的55个具体做法 (第三版)",
  "parallelTitle": "Effective C++: 55 Specific Ways to Improve Your Programs and Designs",
  "seriesTitle": "传世经典书丛",
  "author": "[美] Scott Meyers 著; 侯捷 译",
  "languageCode": "chi",
  "description": "本书不是读完一遍就可以束之高阁的快餐读物，也不是用以解决手边问题的参考手册，而是需要您去反复阅读体会的，C++是真正程序员的语言，背后后精神的思想与无以伦比的表达能力，这使得它具有类似宗教般的魅力。希望这本书能够帮您跨越C++的重重险阻，领略高处才有的壮美风光，做一个成功而快乐的C++程序员。",
  "publisher": "电子工业出版社",
  "clcNumber": "TP312",
  "publicationDate": "2011-01",
  "pricing": "65.00",
  "totalPages": "297",
  "binding": "平装",
  "suitFlag": false
}
