=== ZKLlab/shuosc-books/schema/metadata.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Metadata",
  "description": "SHUOSC图书元信息",
  "type": "object",
  "properties": {
    "isbn": {
      "description": "ISBN号",
      "type": "string",
      "pattern": "^978\\d{10}$"
    },
    "title": {
      "description": "题名",
      "type": "string"
    },
    "parallelTitle": {
      "description": "并列题名",
      "type": [
        "string",
        "null"
      ]
    },
    "seriesTitle": {
      "description": "丛书名",
      "type": [
        "string",
        "null"
      ]
    },
    "author": {
      "description": "责任者",
      "type": "string"
    },
    "languageCode": {
      "description": "正文语种",
      "type": "string",
      "pattern": "^[a-z]{3}$"
    },
    "description": {
      "description": "内容简介",
      "type": "string"
    },
    "publisher": {
      "description": "出版社",
      "type": "string"
    },
    "clcNumber": {
      "description": "中图分类号",
      "type": [
        "string",
        "null"
      ]
    },
    "publicationDate": {
      "description": "出版时间",
      "type": "string",
      "pattern": "^\\d{4}-(0\\d|1[012])$"
    },
    "pricing": {
      "description": "定价",
      "type": "string",
      "pattern": "^([1-9]\\d*|0)\\.\\d{2}$"
    },
    "totalPages": {
      "description": "页数",
      "type": "string",
      "pattern": "^[1-9]\\d*$"
    },
    "binding": {
      "description": "装帧",
      "type": "string"
    },
    "suitFlag": {
      "type": "boolean"
    }
  },
  "required": [
    "isbn",
    "title",
    "parallelTitle",
    "seriesTitle",
    "author",
    "languageCode",
    "description",
    "publisher",
    "clcNumber",
    "publicationDate",
    "pricing",
    "totalPages",
    "binding",
    "suitFlag"
  ],
  "additionalProperties": false
}

=== ZKLlab/shuosc-books/data/metadata/9787115376756__领域驱动设计__软件核心复杂性应对之道.json
{
  "isbn": "9787115376756",
  "title": "领域驱动设计: 软件核心复杂性应对之道",
  "parallelTitle": "Domain-Driven Design: Tackling Complexity in the Heart of Software",
  "seriesTitle": null,
  "author": "[美] Eric Evans 著; 赵俐, 盛海艳, 刘霞 译",
  "languageCode": "chi",
  "description": "本书是领域驱动设计方面的经典之作。全书围绕着设计和开发实践，结合若干真实的项目案例，向读者阐述如何在真实的软件开发中应用领域驱动设计。书中给出了领域驱动设计的系统化方法，并将人们普遍接受的一些最佳实践综合到一起，融入了作者的见解和经验，展现了一些可扩展的设计最佳实践、已验证过的技术以及便于应对复杂领域的软件项目开发的基本原则。",
  "publisher": "人民邮电出版社",
  "clcNumber": "TP311.5",
  "publicationDate": "2016-06",
  "pricing": "69.00",
  "totalPages": "370",
  "binding": "平装",
  "suitFlag": false
}

=== ZKLlab/shuosc-books/data/metadata/9787115293688__程序员的数学.json
{
  "isbn": "9787115293688",
  "title": "程序员的数学",
  "parallelTitle": null,
  "seriesTitle": "图灵程序设计丛书",
  "author": "[日] 结城浩 著; 管杰 译",
  "languageCode": "chi",
  "description": "本书面向程序员介绍了编程中常用的数学知识，借以培养初级程序员的数学思维。书中讲解了二进制计数法、逻辑、余数等许多与编程密切相关的数学方法，分析了哥尼斯堡七桥问题、汉诺塔、斐波那契数列等经典问题和算法，引导读者深入理解编程中的数学方法和思路。",
  "publisher": "人民邮电出版社",
  "clcNumber": "TP301.6",
  "publicationDate": "2012-10",
  "pricing": "49.00",
  "totalPages": "232",
  "binding": "平装",
  "suitFlag": true
}

=== ZKLlab/shuosc-books/data/metadata/9787111618331__设计模式__可复用面向对象软件的基础__典藏版.json
{
  "isbn": "9787111618331",
  "title": "设计模式: 可复用面向对象软件的基础 (典藏版)",
  "parallelTitle": "Design Patterns: Elements of Reusable Object-Oriented Software",
  "seriesTitle": "计算机科学丛书",
  "author": "[美] Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides 著; 李英军, 马晓星, 蔡敏, 刘建中 等译",
  "languageCode": "chi",
  "description": "本书结合设计实例从面向对象的设计中精选出23个设计模式, 总结了面向对象设计中颇有价值的经验, 并且用简洁可复用的形式表达出来。本书分类描述了一组设计良好、 表达清楚的软件设计模式, 这些模式在实用环境下特别有用。 本书适合大学计算机专业的学生、研究生及相关人员参考。",
  "publisher": "机械工业出版社",
  "clcNumber": "TP312.8",
  "publicationDate": "2019-05",
  "pricing": "79.00",
  "totalPages": "290",
  "binding": "平装",
  "suitFlag": false
}

=== ZKLlab/shuosc-books/data/metadata/9787121363511__混沌工程__Netflix系统稳定性之道.json
{
  "isbn": "9787121363511",
  "title": "混沌工程: Netflix系统稳定性之道",
  "parallelTitle": "Chaos Engineering",
  "seriesTitle": null,
  "author": "[美] Lorin Hochstein, Aaron Blohowiak, Nora Jones, Ali Basiri 著; 侯杰 译",
  "languageCode": "chi",
  "description": "近年来，随着服务化、微服务和持续集成的逐渐普及，从开发到线上的便捷性大幅提高。我们在使用这些便利性所带来的好处的同时，对其负面性的问题也要有所认知。尤其是在一个复杂的分布式服务体系中，故障发生的随机性和不可预测性都大大增加了。快速迭代的门槛越来越低，但是对复杂系统稳定性的考验却在成倍增长。在这条路上，各家都有自己的经验实践。混沌工程从出现到标准化成为一门学科，是伴随着Netflix过去三年多时间里同稳定性持续战斗的历程一起成长起来的，这是每一次故障带来的深度思考，抽象而成的理论和实践的结合。混沌工程是一门相对高级的系统稳定性治理方法论，它提倡采用探索式的研究实验，发现生产环境中的各种风险。",
  "publisher": "电子工业出版社",
  "clcNumber": "TP338.8",
  "publicationDate": "2019-08",
  "pricing": "45.00",
  "totalPages": "120",
  "binding": "平装",
  "suitFlag": false
}

=== ZKLlab/shuosc-books/data/metadata/9787111530367__汇编语言__基于x86处理器__原书第7版.json
{
  "isbn": "9787111530367",
  "title": "汇编语言: 基于x86处理器 (原书第7版)",
  "parallelTitle": "Assembly Language for x86 Processors (7th Edition)",
  "seriesTitle": "计算机科学丛书",
  "author": "[美] Kip Irvine 著; 贺莲, 龚奕利 译",
  "languageCode": "chi",
  "description": "本书介绍x86和Intel64处理器的汇编语言编程与架构。前9章为汇编语言的核心概念，包括：汇编语言基础，x86处理器架构，数据传送、寻址和算术运算，过程，条件处理，整数运算，高级过程，以及字符串和数组。后4章介绍结构和宏、MS-Windows编程、浮点数处理和指令编码，以及高级语言接口。",
  "publisher": "机械工业出版社",
  "clcNumber": "TP313",
  "publicationDate": "2016-03",
  "pricing": "99.00",
  "totalPages": "527",
  "binding": "平装",
  "suitFlag": false
}

=== ZKLlab/shuosc-books/data/metadata/9787111445333__应用密码学__协议_算法与C源程序__原书第2版.json
{
  "isbn": "9787111445333",
  "title": "应用密码学: 协议、算法与C源程序 (原书第2版)",
  "parallelTitle": "Applied Cryptography: Protocols, Algorithms, and Source Code in C",
  "seriesTitle": "计算机科学丛书",
  "author": "[美] Bruce Schneier 著; 吴世忠, 祝世雄, 张文政 等译",
  "languageCode": "chi",
  "description": "密码学的应用领域远远不只是编码和解码信息，要了解有关密码学技术的数字签名的知识，本书是必读之作。本书介绍了密码学协议的通用类型、特定技术，详细介绍了现实世界密码学算法的内部机制，包括DES和RSA公开密钥加密系统。书中提供了源代码列表和大量密码学应用方面的实践活动，如产生真正的随机数和保持密钥安全的重要性。",
  "publisher": "机械工业出版社",
  "clcNumber": "TN918.1",
  "publicationDate": "2014-01",
  "pricing": "79.00",
  "totalPages": "545",
  "binding": "平装",
  "suitFlag": false
}

=== ZKLlab/shuosc-books/data/metadata/9787121149528__深度探索C_对象模型.json
{
  "isbn": "9787121149528",
  "title": "深度探索C++对象模型",
  "parallelTitle": "Inside the C++ Object Model",
  "seriesTitle": "传世经典书丛",
  "author": "[美] Stanley B. Lippman 著; 侯捷 译",
  "languageCode": "chi",
  "description": "Inside The C++ Object Model专注于C++对象导向程序设计的底层机制，包括结构式语意、暂时性对象的生成、封装、继承，以及虚拟——虚拟函数和虚拟继承。这本书让你知道：一旦你能够了解底层实现模型，你的程序代码将获得多么大的效率。Lippman澄清了那些关于C++额外负荷与复杂度的各种错误信息和迷思，但也指出其中某些成本和利益交换确实存在。他阐述了各式各样的实现模型，指出它们的进化之道及其本质因素。本书涵盖了C++对象模型的语意暗示，并指出这个模型是如何影响你的程序的。",
  "publisher": "电子工业出版社",
  "clcNumber": "TP312",
  "publicationDate": "2011-12",
  "pricing": "69.00",
  "totalPages": "320",
  "binding": "平装",
  "suitFlag": false
}

=== ZKLlab/shuosc-books/data/metadata/9787115308108__具体数学__计算机科学基础__第2版.json
{
  "isbn": "9787115308108",
  "title": "具体数学: 计算机科学基础 (第2版)",
  "parallelTitle": "Concrete Mathematics: A Foundation for Computer Science",
  "seriesTitle": "图灵计算机科学丛书",
  "author": "[美] Ronald L. Graham, Donald E. Knuth, Oren Patashnik 著; 张明尧, 张凡 译",
  "languageCode": "chi",
  "description": "本书是一本在大学中广泛使用的经典数学教科书。书中讲解了许多计算机科学中用到的数学知识和技巧，教你如何把一个实际问题一步步演化为数学模型，然后通过计算机解决它，特别着墨于算法分析方面，其主要内容涉及和式、整值函数、数论、二项式系数、特殊的数、生成函数、离散概率、渐近式等，都是编程所必备的知识。",
  "publisher": "人民邮电出版社",
  "clcNumber": "TP301.6",
  "publicationDate": "2013-04",
  "pricing": "99.00",
  "totalPages": "562",
  "binding": "平装",
  "suitFlag": false
}
